# Generated by Django 3.2.12 on 2022-10-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('subject', models.CharField(max_length=10)),
                ('question_text', models.CharField(max_length=500)),
                ('notes', models.CharField(max_length=500)),
                ('removed', models.BooleanField()),
                ('tags', models.ManyToManyField(to='questions.Tag')),
            ],
        ),
    ]
