# Generated by Django 3.2.15 on 2022-10-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='notes',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
